### ISSUE TITLE
Add an Event

### ISSUE THREAD

**Issue by carolinectan** [tvaroglu/spot_me_frontend#10]
As an authenticated user, 
when I visit my dashboard:
- I see a list of the gyms of which I am a member
- When I click a Gym, I am redirected to the Gym Show page, and I see a 'Request a Spot' button next to each gym member
- When I click on the button
I am redirected to the Create Event page
And I see a form that has the following fields:
- [ ] gym name (as un-editable field)
- [ ] pick date and time
- [ ] invite an existing friend to the event

When I fill in the form and click submit
I am redirected to my dashboard 
And I see the new event in the 'My Upcoming Workouts' section

**Comment by Scott-Borecki** [comment]
This is a duplicate issue
