### ISSUE TITLE
Gym Show: Add Friend Button

### ISSUE THREAD

**Issue by carolinectan** [tvaroglu/spot_me_frontend#8]
As an authenticated User,
When I visit a Gym Show page of which I am a Gym Member
I see a section to Add Gym Members as Friends
And within this section,
I see a button to 'Add Friend'
When I click the 'Add Friend' button,
I am redirected to the same Gym Show page
And I see my new friend in the My Friends at [Gym Name] section

Note: The Gym must have Gym Members that are not my Friend in order to be displayed in the Add Gym Members as Friends section.

**Comment by tvaroglu** [comment]
Duplicate issue, see this [Issue](https://github.com/tvaroglu/spot_me_frontend/issues/21) for current requirements
